### ISSUE TITLE
Error in running API except ALTextToSpeech or ALMotion

### ISSUE THREAD

**Issue by supermario111** [uts-magic-lab/pynaoqi_mate#1]
Hi,
Thank you for your work and reference

I am trying to run all your API's as per mentioned in your pynaoqi_mate. But I am getting an error almost on all the APIs that is for example:

Traceback (most recent call last):
  File "<pyshell#66>", line 1, in <module>
    m.ALBonjour.force_connect()
  File "C:\Python27\pynaoqi_mate-master\naoqi_proxy_python_classes\ALBonjour.py", line 15, in force_connect
    self.proxy = ALProxy("ALBonjour")
  File "C:\Python27\Lib\site-packages\pynaoqi-python2.7-2.5.5.5-win32-vs2013\lib\naoqi.py", line 233, in __init__
    inaoqi.proxy.__init__(self, args[0])
  File "C:\Python27\Lib\site-packages\pynaoqi-python2.7-2.5.5.5-win32-vs2013\lib\inaoqi.py", line 270, in __init__
    this = _inaoqi.new_proxy(*args)
RuntimeError: 	ALProxy::ALProxy
	Can't find service: ALBonjour

Please write on this concern

**Comment by awesomebytes** [comment]
Looks like you are using Windows, I've never tried to use it on Windows.

Also make sure you are using the branch of the version of naoqi your robot
uses. The branch called something like latest_naoqi is for version 2.5.5.5
